title: "Víctor Muñoz Flores"

description: >
  Académico, Investigador e Ingeniero Civil Industrial.

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed

author:
  name: Víctor Muñoz Flores
  email: vimunozf@outlook.com

header_pages:
  - investigacion.md
  - publicaciones.md
  - proyectos.md
  - docencia.md
  - software.md
  - medios.md
  - cv.md
  - contacto.md
